---
ansible_connection: network_cli
ansible_become: yes
ansible_become_method: enable
ansible_network_os: iosxr
ansible_user: ansi
ansible_password: C1sc0123!
allowed_vlans: 10-20,40
native: 10

SNMP:
  acl_name: NMS-SERVER
#  snmp-server location D1 Rack 1
#  snmp-server contact Student 555-1213
#  snmp-server chassis-id Cisco Device D1
  location: "swtlab"
  contact: "swt"
  chassis_id: "IOSXR-R1xr"
  community:
    rw: "true"
    name: "SwtLabCommunity"
  NMSaddr: "192.168.1.50"
  ver: "2c"
  # snmp-server enable traps
  traps_enable: true
  enabled_traps:
    config: true
    hsrp: true
    ipsla: true
    ntp: true
    ospf: true
...
