---
- name: Get date
  hosts: localhost
  gather_facts: true
  tasks:

    - name: Config Timestamp
      ansible.builtin.set_fact:
        dtg: "{{ ansible_date_time.iso8601 }}"
      tags: gettime

- name: Pre CRQ config backup
  hosts: routersxr,switches
  gather_facts: false
  tags: backup
  vars:
    pref: PRE-CRQ
  roles:
    - backup_config

- name: Apply switch configs
  hosts: switches
  gather_facts: false
  tags: basic
  roles:
    - sw_ip_routing
    - sw_interfaces
    - ios_rtr_interfaces

- name: Configuring Basic Settings (Addr,Banner)
  hosts: all
  gather_facts: false
  tags: basic
  roles:
    - motd_banner
    - role: iosxr_interfaces
      when: ansible_net_system == "iosxr"
    - role: ospf
      when: ansible_net_system == "ios"

- name: Configuring ACLs
  hosts: routersxr
  gather_facts: false
  tags: acls
  roles:
    - role: acls
      when: ACLs is defined

- name: Applying additional settings
  hosts: all
  gather_facts: false
  tasks:
    - name: Additional commands which needs to be applied
      cisco.ios.ios_config:
        lines:
          - "{{ item.opt }}"
      loop: "{{ other_settings }}"
      loop_control:
        label: "{{ item.opt }}"
      when:
        - "other_settings is defined"
        - "ansible_net_system == 'ios'"

# - name: Pause for OSPF to converge
#   hosts: localhost
#   tasks:
#     - name: Add pasue task
#       ansible.builtin.pause:
#         seconds: 15

- name: Set SNMP & Syslog settings on IOSXR
  hosts: routersxr
  gather_facts: false
  roles: 
    - role: snmp
    - role: syslog

- name: Post CRQ config backup
  hosts: all
  tags: backup
  gather_facts: false
  vars:
    pref: POST-CRQ
  roles:
    - backup_config

...
