---
# tasks file for roles/save_config
- name: IOS >> Save Configuration to NVRAM
  cisco.ios.ios_config:
    save_when: always
  register: output
  when: ansible_net_system == "ios"

# - name: DEBUG >> output
#   ansible.builtin.debug:
#     msg: "{{ output }}"
