interfaces:
 - name: Ethernet0/0
   description: Link to R1 configured by Ansible
   mode: "access"
   access_vlan: 10
   voice_vlan: 50

 - name: Vlan 10
   description: Link to R1 configured by Ansible
   ipv4: 192.168.1.2/24


# router ospf 123
#  router-id 1.1.1.2
#  auto-cost reference-bandwidth 1000
#  network 10.10.0.0 0.0.3.255 area 0
#  exit

ospf:
  process_id: 1
  router_id: 1.1.1.2
  default_orignate: "False"
  auto_cost:
    reference_bandwidth: 1000

ospf_networks:
    - address: "192.168.1.0"
      wildcard_bits: "0.0.0.255"
      area: "1"

other_settings:
  - opt: "ip default-gateway 192.168.1.1"
  - opt: "no ip domain lookup"