interfaces:
 - name: GigabitEthernet0/0/0/0 
   description: Link to R2 configured by Ansible
   ipv4: 192.168.12.1/30
   ipv6: 2001:db8:acad:12::1/64
  #  link_local: fe80::12:1


 - name: GigabitEthernet0/0/0/1
   description: Link to D1 configured by Ansible
   ipv4: 192.168.1.1/24
   ipv6: 2001:db8:acad:11::1/64
  #  link_local: fe80::11:1
   cdp: 'no'


# OSPF config data for iosxr
ospf:
  process_id: 1
  router_id: 1.1.1.1
  default_orignate: "false"
  auto_cost:
    reference_bandwidth: "1000"
  areas:
    - area_id: 0.0.0.0
      interfaces:
        - name: GigabitEthernet0/0/0/0
          network: "point-to-point"
          passive: "false"
    - area_id: 0.0.0.1
      interfaces:
        - name: GigabitEthernet0/0/0/1
          network: point-to-point
          passive: "false"

## Below section only required for IOS not IOSxr
ospf_networks:
    - address: "192.168.12.0"
      wildcard_bits: "0.0.0.3"
      area: "0"
    - address: "192.168.1.0"
      wildcard_bits: "0.0.0.255"
      area: "1"

# Additional static routes
# routes:
#   - route: 1
#     dest: "0.0.0.0/0"
#     nexthop: "64.100.0.1"
#     name: "Default_to_R2"

#ip route 0.0.0.0 0.0.0.0 64.100.0.1

other_settings:
  - opt: "no ip domain lookup"

ACLs:
- interface: GigabitEthernet0/0/0/1
  acl_name: "AREA1-TO-AREA2"
  direction: "in"  

- interface: GigabitEthernet0/0/0/1
  acl_name: "AREA2-TO-AREA1"
  direction: "out"    

# SNMP:
#   acl_name: NMS-SERVER
# #  snmp-server location D1 Rack 1
# #  snmp-server contact Student 555-1213
# #  snmp-server chassis-id Cisco Device D1
#   location: "swtlab"
#   contact: "swt"
#   chassis_id: "IOSXR-R1xr"
#   community:
#     rw: "true"
#     name: "SwtLabCommunity"
#   NMSaddr: "192.168.1.50"
#   ver: "2c"
#   # snmp-server enable traps
#   traps_enable: true
#   enabled_traps:
#     config: true
#     hsrp: true
#     ipsla: true
#     ntp: true
#     ospf: true
